version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules

  mongo:
    image: mongo:5.0.8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=pitchr

volumes:
  node_modules: {}
